version: "3.9"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restaurant
    ports:
      - "5433:5432"

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
